language: php

php: ["5.5"]

env:
  global:
    - ARCHER_PUBLISH_VERSION=5.5
    - secure: "O+moLnMxVC4v+KKbB7oyoOF380Ctgg5H/tUWKe9mf+aXNy6UOj96oKmo9cUKpgeAyIkqho9k1eq+kNBLQ1mDhNYs5exmgNFQFjcJTYRrIf+chT/VDJ+cgMq7yoASX5ZLn/oAOvbQIGtyqSQhw4wB1WzhghZN5lnyJS1W3TMoh7Y="

install:
  - ./.travis.install

script:
  - ./vendor/bin/archer travis:build
